apiVersion: 1

providers:
  - name: arex
    orgId: 1
    folder: arex
    folderUid: arex
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: false
    options:
      path: /var/lib/grafana/dashboards/arex
