#!/usr/bin/env bash
# Regenerate the per-consumer rule files from monitoring/alerts.yaml.
#
# The rules exist once. Every consumer below reads the same "groups:" document;
# they differ only in what wraps it, so the wrappers are generated rather than
# maintained, and CI fails if they drift from the source.
set -euo pipefail

export LC_ALL=C

repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_dir"

source_file="monitoring/alerts.yaml"
if [[ ! -f "$source_file" ]]; then
	printf 'gen-monitoring: %s is missing\n' "$source_file" >&2
	exit 1
fi

# The source with its file-level comment block removed and indented, ready to
# sit under a CR's spec. Comments inside the rules are kept: they explain why a
# rule is shaped the way it is, and that is worth carrying into the cluster.
body="$(awk '
	BEGIN { started = 0 }
	/^groups:/ { started = 1 }
	started { print }
' "$source_file" | sed '/^$/! s/^/  /')"

generated_note() {
	printf '# Generated by hack/gen-monitoring.sh from monitoring/alerts.yaml. Do not edit.\n'
	printf '#\n'
	printf '# Edit the rules there and regenerate, or the two will disagree about what\n'
	printf '# fires. CI checks that this file is current.\n'
}

# prometheus-operator, and anything that consumes its CRs: Thanos Ruler through
# the operator, and Grafana Alloy's mimir.rules.kubernetes, which syncs
# PrometheusRule objects to a Mimir ruler.
{
	generated_note
	cat <<-'HEADER'
		---
		apiVersion: monitoring.coreos.com/v1
		kind: PrometheusRule
		metadata:
		  name: arex
		  labels:
		    app.kubernetes.io/name: arex
		    # Some Prometheus deployments select rules by label. Check the
		    # ruleSelector on your Prometheus resource before applying this.
		    prometheus: kube-prometheus
		    role: alert-rules
		spec:
	HEADER
	printf '%s\n' "$body"
} >monitoring/prometheusrule.yaml

# VictoriaMetrics operator. Same schema, different kind and API group.
{
	generated_note
	cat <<-'HEADER'
		---
		apiVersion: operator.victoriametrics.com/v1beta1
		kind: VMRule
		metadata:
		  name: arex
		  labels:
		    app.kubernetes.io/name: arex
		spec:
	HEADER
	printf '%s\n' "$body"
} >monitoring/vmrule.yaml

for f in monitoring/prometheusrule.yaml monitoring/vmrule.yaml; do
	printf 'gen-monitoring: wrote %s (%s lines)\n' "$f" "$(wc -l <"$f" | tr -d ' ')" >&2
done
