// Package legal exposes the legal notices embedded in every binary.
package legal

import _ "embed"

// thirdPartyNotices is generated by hack/gen-notices.sh and checked by CI, so
// a dependency added without regenerating fails the build rather than shipping
// an image whose notices are incomplete.
//
//go:embed THIRD_PARTY_NOTICES
var thirdPartyNotices string

// ThirdPartyNotices returns the dependency licenses and attribution notices
// embedded at build time.
func ThirdPartyNotices() string {
	return thirdPartyNotices
}
